# Lifecycle of hooks : ApplicationStop -> BeforeInstall -> AfterInstall -> ApplicationStart
version: 0.0
os: linux
files:
    - source: /
      destionation: /var/www/html
      overwrite: true
hooks:
    BeforeInstall:
        - location: scripts/install_dependencies.sh
          timeout: 300
          runass: root
    AfterInstall:
        - location: scripts/install_composer_dependencies.sh
          timeout: 300
          runass: root
        - location: scripts/start_server.sh
          timeout: 30
          runass: root
    ApplicationStop:
        - location: scripts/application_stop.sh
          timeout: 300
          runass: root
    